version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nacos:
    image: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
