CREATE TABLE TBL_ACC_ACCOUNT(
                                ID BIGINT(20) NOT NULL AUTO_INCREMENT  COMMENT '主键;主键' ,
                                CUST_NO VARCHAR(32) NOT NULL   COMMENT '客户账号;对应客户表客户编号' ,
                                BLNG_OBJCT_NO VARCHAR(32) NOT NULL   COMMENT '商户号或机构号;账户所属收单商户的商户号或者机构号' ,
                                PRM_TP CHAR(2) NOT NULL   COMMENT '账户类别属性:;账户类别属性:保证金账户	01商户待结算账户	02平台待结算账户	03个人子账户	04商户子账户	05商户-营销子账户	07银行-营销子账户	08平台-营销子账户	09平台-手续费账户	10' ,
                                BLNG_SUBJ_NO VARCHAR(32) NOT NULL   COMMENT '账户所属科目;对应科目表科目代码' ,
                                ACCT_NO VARCHAR(32) NOT NULL   COMMENT '账户号;命名规则;总行机构码（4位）+产品码（4位）+账户类别（2位）+平台编号+顺序号，核心屏蔽收单使用的产品码' ,
                                ACCT_NM VARCHAR(32) NOT NULL   COMMENT '账户名称;对于个人存放姓名对于企业存放公司简称' ,
                                ACC_STATUS VARCHAR(32) NOT NULL   COMMENT '账户状态;NORMAL;–正常 CLOSED – 被关闭，不能有账务往来 NOIN - 禁止入账 NOOUT - 禁止出账' ,
                                SETTLE_NO VARCHAR(128)    COMMENT '账户对应的实体卡号;实体账户卡号' ,
                                SETTLE_NM VARCHAR(255)    COMMENT '账户对应实体账号账户名称;账户对应实体账号账户名称' ,
                                CCY VARCHAR(3) NOT NULL   COMMENT '币种;156 人名币' ,
                                ACCT_AVL_BAL DECIMAL(12,2)    COMMENT '账户可用余额' ,
                                ACCT_FRZ_BAL DECIMAL(12,2)    COMMENT '账户冻结余额' ,
                                ACCT_BAL DECIMAL(12,2)    COMMENT '账户余额' ,
                                ACCT_BAL_DCD_RCTN VARCHAR(2)    COMMENT '账户余额借贷方向' ,
                                LST_ACCG_DT DATE    COMMENT '上期账务日期' ,
                                ACCT_EFFCT_TM DATETIME NOT NULL   COMMENT '账户生效时间' ,
                                ACCT_INVLD_TM DATETIME    COMMENT '账户失效时间' ,
                                OVRDRFT_FLG CHAR(2)    COMMENT '可透支标识;（Y;-可透支；N-不可透支）' ,
                                PRTCL_UPDT_FLG CHAR(2)    COMMENT '实时更新标识;（Y-实时更新；N-日终更新）' ,
                                ENB_FLG CHAR(1) NOT NULL   COMMENT '启用标志;0-;不启用1- 启用' ,
                                BAK1 VARCHAR(128)    COMMENT '' ,
                                BAK2 VARCHAR(128)    COMMENT '' ,
                                BAK3 VARCHAR(128)    COMMENT '' ,
                                BAK4 VARCHAR(255)    COMMENT '' ,
                                BAK5 VARCHAR(255)    COMMENT '' ,
                                CREATED_BY VARCHAR(32)    COMMENT '创建人' ,
                                CREATED_TIME DATETIME    COMMENT '创建时间' ,
                                UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
                                UPDATED_TIME DATETIME    COMMENT '更新时间' ,
                                PRIMARY KEY (ID)
)  COMMENT = '客户账户表';
